[package]
name = "advent-of-code-2024"
version = "0.1.0"
edition = "2021"
authors = ["Rob Parker"]
description = "Advent of Code 2024 solutions."
repository = "https://github.com/jademonkey/advent-of-code-2024"
publish = false

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
